### ISSUE TITLE
OpenHAB2

### ISSUE THREAD

**Issue by ghost** [octa22/org.openhab.binding.somfytahoma#1]
Hello @octa22 

thank you for your effort to make Somfy Tahoma (if not io homecontrol) working with OpenHAB. This is indeed one of the most missing parts for me.

Yet, I have not managed to get this built nor working, due to a lack of experience. Wouldn't it be possible, to provide a .jar file or - better - integrate it into the OpenHAB 2 bindings in Paper UI?

Your benefit would be a broader user basis, that will report issues, problems and can help enhance the binding.

Also a question regarding OpenHAB2 which is not documents: what are the correct "channel=" definitions in OpenHAB2 item files?

Thank you once again for your effort!

**Comment by octa22** [comment]
Hello, since this is a OH1 binding there are no OH2 channels and things. I'm sorry I'm still not using OH2 since I have everything built on OH1 and migration to OH2 still means loosing some functionality for me. If you want to use this binding in OH2 you have to use it OH1 way - as described in readme { somfytahoma="..." }. It should be working.

**Comment by ghost** [comment]
Thanks a lot. Perhaps you can help out the other guy here in the discussion? https://community.openhab.org/t/tahoma-binding-compatible-with-oh2/27004/4

**Comment by octa22** [comment]
Hello, here is the OH2 version of this binding...
https://github.com/octa22/openhab2-addons/tree/master/addons/binding/org.openhab.binding.somfytahoma

**Comment by ghost** [comment]
Hello @octa22 

the link leads to a 404 error page :(

Here's a link that works: https://github.com/octa22/openhab2-addons/tree/somfytahoma-binding/addons/binding/org.openhab.binding.somfytahoma

I also managed to get it running in OpenHAB 2.1 after I put the jar into the /usr/share/openhab2/addons folder. Downloaded the file from https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.somfytahoma/2.2.0-SNAPSHOT/org.openhab.binding.somfytahoma-2.2.0-SNAPSHOT.jar

Thanks a lot for you effort! :)
