### ISSUE TITLE
Connexoon compatible

### ISSUE THREAD

**Issue by tommem07** [octa22/org.openhab.binding.somfytahoma#2]
Hi octa22,
Thanks for your effort. Does the binding supports connexoon?

**Comment by octa22** [comment]
This binding connects to tahomalink API. Does connexoon have some cloud web interface? Is it www.tahomalink.com? If so, there is a chance it could work. Unfortunately I do not own connexoon device and I canbot test it.

**Comment by tommem07** [comment]
Hi @octa22,
You were right. coonexoon uses the same API. It works now. Thanks.
