### ISSUE TITLE
Not able to build binding

### ISSUE THREAD

**Issue by tommem07** [octa22/org.openhab.binding.somfytahoma#3]
Hi @octa22 

Thanks for the effort you put into this binding. Do you know if this also works for connexoon? In addition it would be great, if you could share a new release of the binding. I am not able to build it with maven. 

Thanks.

**Comment by octa22** [comment]
Hi, please see the latest release https://github.com/octa22/org.openhab.binding.somfytahoma/releases/tag/1.11.0-SNAPSHOT
I'll check the build process again, I am sorry you have trouble building this binding.

**Comment by tommem07** [comment]
Thanks
