### ISSUE TITLE
New unknown device 

### ISSUE THREAD

**Issue by gintonic26** [octa22/org.openhab.binding.somfytahoma#4]
`2018-09-23 20:56:13.668 [INFO ] 
[very.SomfyTahomaItemDiscoveryService] - Supported commands: { }

2018-09-23 20:56:13.672 [WARN ] 
[very.SomfyTahomaItemDiscoveryService] - Device states: 
{name='rtds:ControllerOriginatorState', type=1, value=2.0}
{name='rtds:ControllerSensingState', type=3, value=KO}
{name='rtds:ControllerBatteryState', type=3, value=OK}
{name='rtds:ControllerOrderTypeState', type=3, value=off}`

It is a remote control to arm, partial arm and disarm and complete disarm of the system. 
Because it came in the box with my Tahoma and the log tells me to post this here I did this. 
Till now I have no plans to use the remote so there is no time pressure.

**Comment by octa22** [comment]
Hi, could you please provide me with the name of the device? There is missing the beginning of the debug info (a line starting with "Detected a new unsupported device:")
Thanks
Ondrej
