### ISSUE TITLE
 Detected a new unsupported device: NetworkComponent

### ISSUE THREAD

**Issue by Stylewarz3** [octa22/org.openhab.binding.somfytahoma#5]
Detected a new unsupported device: NetworkComponent
Supported commands: { }
Device states:
{name='core:DeviceDefectState', type=3, value=2,8}
{name='core:NeighboursAddressesState', type=3, value=2,8}

https://shop.somfy.de/licht-empfanger-io-an-aus.html

**Comment by octa22** [comment]
Hi,

according to the provided log this device has no possibility to control via API (no commands) and provides only information about defect state and neighbour addresses.
Sorry to tell you, but it makes no sense to add support for this device :-(
